name: Build & Deploy SPA

on:
  push:
    branches:
      -caballero

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar dependencias
        run: npm install

      - name: ğŸ—ï¸ Build producciÃ³n
        run: npm run build

      - name:  Subir dist al VPS
        uses: appleboy/scp-action@master
        with:
          port: ${{ secrets.VPS_PORT }}
          host: 191.101.1.146
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          
          source: "dist/*"
          #target: "/var/www/control_vehicular"
          #rm: true
          #strip_components: 1
