name: Build & Deploy SPA

on:
  push:
    branches:
      -caballero

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar dependencias
        run: npm install

      - name: ğŸ—ï¸ Build producciÃ³n
        run: npm run build

      - name:  Subir dist al VPS
        uses: appleboy/scp-action@master
        with:
          
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USER }}
              key: ${{ secrets.VPS_SSH_KEY }}
              source: dist/*
              target: /var/www/control_vehicular
              rm: true
              port: 6125
              timeout: 30s
              command_timeout: 10m
              use_insecure_cipher: false
              debug: false
              strip_components: 0
              overwrite: false
              tar_dereference: false
              tar_exec: tar
              proxy_port: 6125
              proxy_timeout: 30s
              proxy_use_insecure_cipher: false
  
